version: "3.8"
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: "sqlserver"
    environment:
      MSSQL_SA_PASSWORD: TUC:GR8?MHYP
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
