version: "3.8"
services:
  db:
    container_name: project_db
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: TUC:GR8?MHYP
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    networks:
      - local

  backend:
    image: academy/teaminator-back:latest
    environment:
      TYPEORM_HOST: project_db
      SPRING_DATA_SOURCE_URL: ${SPRING_DATA_SOURCE_URL}
      SPRING_DATA_SOURCE_USERNAME: ${SPRING_DATA_SOURCE_USERNAME}
      SPRING_DATA_SOURCE_PASSWORD: ${SPRING_DATA_SOURCE_PASSWORD}
    container_name: webservice
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - local

networks:
  local:
    driver: bridge