package codurance.academyfinalboy.backend;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.URISyntaxException;
import java.security.GeneralSecurityException;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;


public class GoogleTokenValidatorShould {
    String validToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlYzEzZGViZjRiOTY0Nzk2ODM3MzYyMDUwODI0NjZjMTQ3OTdiZDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI2NzEyMDg1NDgyNTMtaHJkNWE0bnZyazRvdnNzY2Zza3Byc2JvZG43YXRlOGsuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI2NzEyMDg1NDgyNTMtaHJkNWE0bnZyazRvdnNzY2Zza3Byc2JvZG43YXRlOGsuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDM1NTg0NTMyOTk2MTkxMTUzNjIiLCJoZCI6ImNvZHVyYW5jZS5jb20iLCJlbWFpbCI6ImJyaWFuLmhkLmhvYW5nQGNvZHVyYW5jZS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiYXRfaGFzaCI6IkNIQnRQQVJnZTBMc0dmSkRRVmJpUWciLCJuYW1lIjoiQnJpYW4gSG9hbmciLCJwaWN0dXJlIjoiaHR0cHM6Ly9saDMuZ29vZ2xldXNlcmNvbnRlbnQuY29tL2EtL0FPaDE0R2lDdWM2TFdXZGpvc3BhX25WbFJqdGJZeUpxcktQbFRUb3pCdlNzPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IkJyaWFuIiwiZmFtaWx5X25hbWUiOiJIb2FuZyIsImxvY2FsZSI6ImVuLUdCIiwiaWF0IjoxNjQ5MzQ0Njg3LCJleHAiOjE2NDkzNDgyODd9.INap-ENWY8JtZAyEUSJBw_E9sPylWfYVmS0KDKmhjhhq9o6diPP9FhCR_UXG48ahfY8Z-MUdqLoa-1_EdJ-Uc5CAqiOhEn8_vAyWsCqnzpoJvHEoq_6mc5CDyUZms608ij3tPxBak-D5abauq0oNZhzBl-1OPGriwN2FoIVQe2_oIXzP6FG_KNN_W9ci42_FhyOZ7G4xH4-Mjn5SOTD2E-6wYyfamK6YGCc4cjtnXwYu8_89xoPjrjP_mPjkkCI9pnvANIptGJA7-uBtggpTv2T8jvS1ji8vJ9C7qSBy_VD76wTpDDA_91EN6cC6geRI3i1I4otrlb6LeZfH3btBZw";
    String invalidToken = "invalid_token";

    @Test
    void return_true_when_token_is_valid() throws GeneralSecurityException, IOException, InterruptedException, URISyntaxException {
        GoogleTokenValidator googleTokenValidator = new GoogleTokenValidator();
        assertTrue(googleTokenValidator.authenticateToken(validToken));
    }
    @Test
    void return_false_when_token_is_invalid() throws Exception {
        GoogleTokenValidator googleTokenValidator = new GoogleTokenValidator();
        assertFalse(googleTokenValidator.authenticateToken(invalidToken));
    }
}
